---
- name: git setup http proxy
  git_config:
    name: http.proxy
    value: "{{ http_proxy }}}"
    scope: global
  when: http_proxy != 'None'

- name: install | Cloning {{ netdata_git_repo }} to {{ netdata_source_dir }}
  git:
    repo: "{{ netdata_git_repo }}"
    dest: "{{ netdata_source_dir }}"
    depth: 1
  become: true

- name: install | Installing Netdata ({{ netdata_installer }}) From {{ netdata_source_dir }}
  command: "{{ netdata_installer }} --dont-wait"
  args:
    chdir: "{{ netdata_source_dir }}"
    creates: "/usr/sbin/netdata"
  become: true
  notify: "restart netdata"
